spring.application.name=api-service-java

sap.cps.base-url=${CPS_API_URL}

sap.cps.uaa-url=${CPS_UAA_URL}
sap.cps.client-id=${CPS_CLIENT_ID}
sap.cps.client-secret=${CPS_CLIENT_SECRET}

app.configurations-db.path=configurations-db